# Steps to System Check
---

- name: Check CPU usage
  shell: mpstat | grep all | awk '{print $3+$5}'
  register: cpu_usage
  become: true
  changed_when: false

- name: Check RAM usage
  shell: free -h | grep Mem | awk '{print $3}'
  register: ram_usage
  changed_when: false

- name: Check Disk usage
  shell: df -hT / | awk 'NR>1 {print $6}'
  register: disk_usage
  become: true
  changed_when: false

- name: Check system uptime
  shell: uptime -p
  register: system_uptime
  become: true
  changed_when: false

- name: Ensure output directory exists
  ansible.builtin.file:
    path: "./output"
    state: directory
    mode: '0755'
    owner: '1000'
    group: '1000'
  delegate_to: localhost

- name: Create Markdown header in the report file
  lineinfile:
    path: "./output/{{ ansible_date_time.year }}-{{ ansible_date_time.month }}-{{ ansible_date_time.day }}_system_report.md"
    line: "| Sunucu İsmi | CPU (%) | RAM (%) | Disk (%) | Up-Time |"
    create: yes
    insertbefore: BOF
    owner: '1000'
    group: '1000'
    mode: '0644'
  delegate_to: localhost
  run_once: true

- name: Add separator for the Markdown table header
  lineinfile:
    path: "./output/{{ ansible_date_time.year }}-{{ ansible_date_time.month }}-{{ ansible_date_time.day }}_system_report.md"
    line: "|-------------|---------|---------|----------|-----------------|"
    owner: '1000'
    group: '1000'
    mode: '0644'
  delegate_to: localhost
  run_once: true

- name: Append system information to the Markdown file
  lineinfile:
    path: "./output/{{ ansible_date_time.year }}-{{ ansible_date_time.month }}-{{ ansible_date_time.day }}_system_report.md"
    line: "| {{ inventory_hostname }} | {{ cpu_usage.stdout }} | {{ ram_usage.stdout }} | {{ disk_usage.stdout }} | {{ system_uptime.stdout }} |"
    owner: '1000'
    group: '1000'
    mode: '0644'
  delegate_to: localhost

