# Steps to Check CPU
---

    - name: Check CPU usage
      shell: mpstat | grep all | awk '{print $3+$5}'
      register: cpu_usage
      become: true
      changed_when: false

    - name: Check RAM usage
      shell: free | grep Mem | awk '{print $3/$2 * 100.0}'
      register: ram_usage
      changed_when: false

    - name: Check Disk usage
      shell: df -h | grep /dev/sda1 | awk '{print $5}'
      register: disk_usage
      become: true
      changed_when: false

    - name: Check system uptime
      shell: uptime -p
      register: system_uptime
      become: true
      changed_when: false

    - name: Create and append system information to a text file
      lineinfile:
        path: "/output/{{ ansible_date_time.date }}_system_report.txt"
        line: |
          Sunucu ismi : {{ inventory_hostname }}
          CPU : {{ cpu_usage.stdout }}%
          RAM : {{ ram_usage.stdout }}%
          DISK : {{ disk_usage.stdout }}
          UP-TIME: {{ system_uptime.stdout }}
        create: yes
      delegate_to: localhost
