# Steps to File Transfer
---

- name: "System Check CPU" 
  ansible.builtin.import_tasks: 01_check_cpu.yml

- name: "System Check RAM" 
  ansible.builtin.import_tasks: 01_check_ram.yml

- name: "System Check DISK" 
  ansible.builtin.import_tasks: 01_check_disk.yml

- name: "System Check UP TIME" 
  ansible.builtin.import_tasks: 01_check_uptime.yml